spring.application.name=salary-management




spring.datasource.url=${DB_URL:jdbc:postgresql://localhost:5432/employee_salary_db}

spring.datasource.username=${DB_USERNAME:postgres}

spring.datasource.password=${DB_PASSWORD}




spring.jpa.hibernate.ddl-auto=update

spring.jpa.show-sql=false

spring.jpa.properties.hibernate.format_sql=false




jwt.secret=${JWT_SECRET}

jwt.expiration=3600000